defaults:
  - mlflow
  - data
  - _self_

is_target_in_data: true
infer_data_path: data/test.csv
save_predictions_path: result/predictions.csv

saved_best_model_path: weights/best_model.pt

batch_size: 16
