defaults:
  - mlflow
  - data
  - model
  - _self_

optimizer:
  _partial_: false
  _target_: torch.optim.Adam
  lr: 1e-3

loss_func:
  _partial_: false
  _target_: torch.nn.CrossEntropyLoss

experiment_name: wine_classification

test_data_path: data/test.csv
train_data_path: data/train.csv
save_best_model_path: weights/best_model.onnx

save_scaler_path: assets/scaler.pkl

model_artifact_path: weights/best_model

seed: 42
batch_size: 8
epoch: 50
use_class_weigths: true
