defaults:
  - data
  - model
  - _self_

optimizer:
  _partial_: false
  _target_: torch.optim.Adam
  lr: 1e-3

loss_func:
  _partial_: false
  _target_: torch.nn.CrossEntropyLoss

dvc_dir_to_load: data

test_data_path: data/test.csv
train_data_path: data/train.csv
save_best_model_path: weigths/best_model.pt

seed: 42
batch_size: 8
epoch: 50
use_class_weigths: true
